[package]
name = "hit-or-miss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "master"
path = "src/master.rs"

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
